name: deploy

on:
  push:
    branches: [master]
    paths-ignore:
      - README.md

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        uses: pnpm/action-setup@v4.0.0
        with:
          version: '8.15.9'
      - run: pnpm install # 安装依赖
      - run: pnpm run docs:build  # 打包文档

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./docs-dist # 3.打包后文件的输出目录(根据你自己的项目情况而定)
          github_token: ${{ secrets.CICD }} # 4.刚才你C下来的仓库token秘钥!!!
          user_name: ${{ secrets.MY_USER_NAME }} # 不用改
          user_email: ${{ secrets.MY_USER_EMAIL }} # 不用改
          commit_message: 自动部署 # 5.部署时的 git 提交信息，自由填写
